### ISSUE TITLE
Geo data of federal Nepal

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/geo#19]
I wonder if we can get geo data of all admin layers of federal Nepal. 

FYI - Central Bureau of Statistics has published [Geographical Coding of States, Districts
and Local units](http://cbs.gov.np/image/data/2017/Geograpgical%20codes%20for%20states,districts%20and%20local%20units/coding_methodology.pdf) (PDF). It does not have geo data - just its methodology for "developing geographic codes for districts and local units so that a uniform set of geographic
codes can be practiced in the country."

@nikeshbalami - if possible, may I request you to suggest links/resources where there is geo files of gaupalika, municipalities, districts, provinces etc?

**Comment by nikeshbalami** [comment]
Hi @ravinepal here goes the links.

753 Local bodies of Nepal (includes Rural Municipality, Municipality, Sub-Metropolitan, Metropolitan): http://ngiip.gov.np/data-center/admin-boundary
Provinces and districts: http://localboundries.oknp.org

**Comment by cliftonmcintosh** [comment]
@nikeshbalami 

~~Do we have geojson and topojson files for provinces?~~ (I see that all levels can be accessed at http://localboundries.oknp.org/)

Are district boundaries the exact same as before?
