### ISSUE TITLE
confirm interpretation of properties sample in README

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/geo#2]
@ravinepal 

I have updated the readme in [this branch](https://github.com/Code4Nepal/geo/tree/original-vdc-properties) to explain how the data was created. Can you verify that my interpretation of the properties for one of the VDCs is correct? If so, there is a pull request out (#1) to merge this into master.

**Comment by ravinepal** [comment]
thank you, @cliftonmcintosh! Yes!
